language: android

android:
  components:
    - build-tools-21.1.2
    - android-19
  licenses:
    - android-sdk-license-5be876d5

before_script:
    - ./gradlew assemble

script:
    - ./gradlew check

jdk:
  - oraclejdk7
